const productosTopsLisos = [
    {
        id: 1,
        nombre: "Top Liso Black",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/lisonegro.png",
    },
    {
        id: 2,
        nombre: "Top Liso Pink ",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/lisorosa1.png",
    },
    {
        id: 3,
        nombre: "Top Liso Fluor",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/lisoverde.png",
    },
    {
        id: 4,
        nombre: "Top Liso Grey",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topliso.png" ,
    },
    
]
const productosTopsEstampados = [
    {
        id: 5,
        nombre: "Top Sara",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/top-sara-geo11-7870b1f80568b06a2a16228130783938-240-0.jpg",
    },
    {
        id: 6,
        nombre: "Top Jungle",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado1.png" ,
    },
    {
        id: 7,
        nombre: "Top Ocean",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado2.png",
    },
    {
        id: 8,
        nombre: "Top Flay",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado3.png",
    },
    {
        id: 9,
        nombre: "Top Micah",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado4.png",
    },
    {
        id: 10,
        nombre: "Top Rulls",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado5.png",
    },
    {
        id: 11,
        nombre: "Top North",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado6.png",
    },
    {
        id: 12,
        nombre: "Top Summer",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado12.png",
    },
    {
        id: 13,
        nombre: "Top Spring",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado8.png",
    },
    {
        id: 14,
        nombre: "Top Muel",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado9.png",
    },
    {
        id: 15,
        nombre: "Top Somu",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado10.png",
    },
    {
        id: 16,
        nombre: "Top Lorei",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/topestampado11.png",
    },
]
const productosMallasBikersLisas = [
    {
        id: 1,
        nombre: "Malla Biker Pink",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso1.png",
    },
    {
        id: 2,
        nombre: "Malla Biker Fluor",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso2.png",
    },
    {
        id: 3,
        nombre: "Malla Biker Grey",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso3.png",
    },
    {
        id: 4,
        nombre: "Malla Biker Black ",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso4.png",
    },

]

const productosMallasBikersEstampadas = [
    {
        id: 5,
        nombre: "Malla Biker Lunar",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada1.png",
    },
    {
        id: 6,
        nombre: "Malla Biker Flower ",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada2.png",
    },
    {
        id: 7,
        nombre: "Malla Biker Jungle",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada3.png",
    },
    {
        id: 8,
        nombre: "Malla Biker Tulip",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada4.png",
    },
    {
        id: 9,
        nombre: "Malla Biker Square",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada5.png",
    },
    {
        id: 10,
        nombre: "Malla Biker Zebra",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada6.png",
    },
    {
        id: 11,
        nombre: "Malla Biker Tiger",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada7.png",
    },
    {
        id: 12,
        nombre: "Malla Biker Laser",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada8.png",
    },
]

const productosMallas34Liso = [
    {
        id: 13,
        nombre: "Malla 3/4 Black",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-1.png",
    },
    {
        id: 14,
        nombre: "Malla 3/4 Rose",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-2.png",
    },
    {
        id: 15,
        nombre: "Malla 3/4 Grey",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-3.png",
    },
]

const productosMallas34Estampado = [
    {
        id: 16,
        nombre: "Malla 3/4 Animal Print",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada1.png",
    },
    {
        id: 17,
        nombre: "Malla 3/4 Rainbow",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada2.png",
    },
    {
        id: 18,
        nombre: "Malla 3/4 Sea",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada3.png",
    },
    {
        id: 19,
        nombre: "Malla 3/4 Ocean",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada4.png",
    },
    {
        id: 20,
        nombre: "Malla 3/4 Rose",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada5.png",
    },
    {
        id: 21,
        nombre: "Malla 3/4 Algae",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada6.png",
    },
    {
        id: 22,
        nombre: "Malla 3/4 Under",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada7.png",
    },
    {
        id: 23,
        nombre: "Malla 3/4 Spring",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada8.png",
    },
]

const productosMallas34Combinado = [
    {
        id: 24,
        nombre: "Malla 3/4 Combinada Summer",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada1.png",
    },
    {
        id: 25,
        nombre: "Malla 3/4 Combinada Rainbow",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada2.png",
    },
    {
        id: 26,
        nombre: "Malla 3/4 Combinada Algae",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada3.png",
    },
    {
        id: 27,
        nombre: "Malla 3/4 Combinada Moon",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada4.png",
    },
]

const productosMallasLisas = [
    {
        id: 28,
        nombre: "Malla Total Grey",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa1.png",
    },
    {
        id: 29,
        nombre: "Malla Total Blue ",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa2.png",
    },
    {
        id: 30,
        nombre: "Malla Total Light Blue",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3.png",
    },
    {
        id: 31,
        nombre: "Malla Total Brown",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa4.png",
    },
    {
        id: 32,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa5.png",
    },
]

const productosMallasEstampadas = [
    {
        id: 33,
        nombre: "Malla Flower",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada1.png",
    },
    {
        id: 34,
        nombre: "Malla Under",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada2.png",
    },
    {
        id: 35,
        nombre: "Malla Spring",
        precio: 30,
        divisa: "€",
        stock: 10,
        src:"./media/images/calzalargaestampada3.png",
    },
    {
        id: 36,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada4.png",
    },
    {
        id: 37,
        nombre: "Malla Moon",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada5.png",
    },
    {
        id: 38,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada6.png",
    },
    {
        id: 39,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada7.png",
    },
    {
        id: 40,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada8.png",
    },
    {
        id: 41,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada9.png",
    },
    {
        id: 42,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada10.png",
    },
    {
        id: 43,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada11.png",
    },
    {
        id: 44,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada12.png",
    },
    {
        id: 45,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada13.png",
    },
    {
        id: 46,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada14.png",
    },
    {
        id: 47,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada15.png",
    },
    {
        id: 47,
        nombre: "Malla Total Pink",
        precio: 30,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalargaestampada16.png",
    },

]

const productoSudadera = [
    {
        id: 48,
        nombre: "Sudadera Total Caqui",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/buzo1.png",
    },
    {
        id: 49,
        nombre: "Sudadera Estampada Ligth",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/buzo2.png",
    },
    {
        id:50,
        nombre: "Sudadera Total Orange",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/buzo3.png",
    },
    {
        id: 51,
        nombre: "Sudadera estampada Riel",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/buzo4.png",
    },
]
const productoPantalones = [
    {
        id: 52,
        nombre: "Pantalon Total Caqui",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/pantalones2.png",
    },
    {
        id: 53,
        nombre: "Pantalon Total Ligth",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/pantalones3.png",
    },
    {
        id: 54,
        nombre: "Pantalon Total Grey",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/pantalones4.png",
    },
    {
        id: 55,
        nombre: "Pantalon Total Rouge",
        precio: 35,
        divisa: "€",
        stock: 10,
        src: "./media/images/pantalones5.png",
    },
]