const productosBikersLisas = [
    {
        id: 1,
        nombre: "Malla Biker Pink",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso1.png",
    },
    {
        id: 2,
        nombre: "Malla Biker Fluor",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso2.png",
    },
    {
        id: 3,
        nombre: "Malla Biker Grey",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso3.png",
    },
    {
        id: 4,
        nombre: "Malla Biker Black ",
        precio: 20,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerliso4.png",
    },

]

const productosBikersEstampadas = [
    {
        id: 5,
        nombre: "Malla Biker Lunar",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada1.png",
    },
    {
        id: 6,
        nombre: "Malla Biker Flower ",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada2.png",
    },
    {
        id: 7,
        nombre: "Malla Biker Jungle",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada3.png",
    },
    {
        id: 8,
        nombre: "Malla Biker Tulip",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada4.png",
    },
    {
        id: 9,
        nombre: "Malla Biker Square",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada5.png",
    },
    {
        id: 10,
        nombre: "Malla Biker Zebra",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada6.png",
    },
    {
        id: 11,
        nombre: "Malla Biker Tiger",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada7.png",
    },
    {
        id: 12,
        nombre: "Malla Biker Laser",
        precio: 22,
        divisa: "€",
        stock: 10,
        src: "./media/images/bikerestampada8.png",
    },
]

const producto34Liso = [
    {
        id: 13,
        nombre: "Malla 3/4 Black",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-1.png",
    },
    {
        id: 14,
        nombre: "Malla 3/4 Rose",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-2.png",
    },
    {
        id: 15,
        nombre: "Malla 3/4 Grey",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/calzalisa3-4-3.png",
    },
]

const producto34Estampado = [
    {
        id: 16,
        nombre: "Malla 3/4 Animal Print",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada1.png",
    },
    {
        id: 17,
        nombre: "Malla 3/4 Rainbow",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada2.png",
    },
    {
        id: 18,
        nombre: "Malla 3/4 Sea",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada3.png",
    },
    {
        id: 19,
        nombre: "Malla 3/4 Ocean",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada4.png",
    },
    {
        id: 20,
        nombre: "Malla 3/4 Rose",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada5.png",
    },
    {
        id: 21,
        nombre: "Malla 3/4 Algae",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada6.png",
    },
    {
        id: 22,
        nombre: "Malla 3/4 Under",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada7.png",
    },
    {
        id: 23,
        nombre: "Malla 3/4 Spring",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4estampada8.png",
    },
]

const producto34Combinado = [
    {
        id: 23,
        nombre: "Malla 3/4 Combinada Summer",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada1.png",
    },
    {
        id: 23,
        nombre: "Malla 3/4 Combinada Rainbow",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada2.png",
    },
    {
        id: 23,
        nombre: "Malla 3/4 Combinada Algae",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada3.png",
    },
    {
        id: 23,
        nombre: "Malla 3/4 Combinada Moon",
        precio: 28,
        divisa: "€",
        stock: 10,
        src: "./media/images/3-4combinada4.png",
    },
]